### ISSUE TITLE
Only getting desktop notification for new alert / message

### ISSUE THREAD

**Issue by Cldfire** [Adriani6/SpigotNotifier#15]
I'm getting desktop notifications for new alerts and messages, but none of the following are happening:
- Notification sound
- Badge on extension icon being changed
- Extension panel 'Notifications' or 'Messages' values being changed
- DOM being changed to display the 'you have x new alerts' red box next to the alert flag

Basically the only thing that appears to be happening is a desktop notification (without sound). Notification sound is enabled, volume is at 100% and pressing the play button to preview the sound works.

**Comment by Adriani6** [comment]
All should be fixed with 1.8.2.

**Comment by Cldfire** [comment]
Hmm, after the latest commits (1.8.2) it doesn't seem to be working at all. Not even getting a desktop notification for new alerts (didn't test messages). I know the extension checked the alerts page because the new alerts red box disappeared.

**Comment by Adriani6** [comment]
I have had a look, my bad, I used the wrong class. I have updated the extension again, hopefully everything is good now. Messages might be bugged (hopefully not though) as I can't test them.

**Comment by Cldfire** [comment]
Both messages and alerts are working now, with one exception. With one new alert and one new message, the extension badge displayed '1' not '2'. My guess would be you forgot to update the badge count for either messages or alerts.

**Comment by Cldfire** [comment]
From my quick glance through, it looks like messages is indeed the type that isn't getting registered on the badge.

https://github.com/Adriani6/SpigotNotifier/blob/master/spigotnotifier.js#L99

Might be wrong though (or message implementation just isn't done yet, which also looks like it's the case).
